

server:
  port: 8011


# For MySQL connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/volleyballbooking?serverTimezone=UTC&useSSL=false
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE